/robot/impedance_settings:
  ros__parameters:
    robot_initial_config: [0.521577,-0.32123,-0.274981,-2.23858,-0.0501384,-0.7823,0.0]
    stiffness_preset: [4000.0,4000.0,4000.0,4000.0,1000.0,1000.0,10.0]
    stiffness_constant: [200.0,200.0,200.0,200.0,200.0,200.0,5.0]
    stiffness_maximum: [4000.0,4000.0,4000.0,4000.0,4000.0,4000.0,10.0]
    damping_preset: [40.0,40.0,40.0,40.0,10.0,10.0,0.5]
    damping_maximum: [70.0,70.0,70.0,70.0,70.0,70.0,1.5]
    wrench_initial: [0.0,0.0,0.0,0.0,0.0,0.0]
    precision_initial: [0.1,0.1,0.1,0.1,0.1,0.1]
    robot_urdf_model_path: "/home/liana/catkin4ros2_ws/src/iit-centauro-ros-pkg/centauro_urdf/urdf/centauro.urdf"
    robot_base_frame_name: "torso_2"
    robot_tip_frame_name: "arm2_8"
    topic_subscriber_name: "/robot/task_planning"
    topic_publisher_name: "ros2_impedance_planning"
    transition_time: 5.0
    rate: 800
    log_path: "/tmp/impedance_planner"
    verbose: false